### ISSUE TITLE
Tables are not rendered correctly

### ISSUE THREAD

**Issue by zznidar** [mpavsic/biokeminfo#1]
Tabele (preglednice) se v spletni verziji ne prikažejo kot tabele, pač pa kot navadno besedilo s pipami, dvopičji, vezaji in citatnimi pomišljaji. Težava je samo na spletu; v Jupyter Notebooku se prikažejo pravilno.

Primer: https://mpavsic.github.io/biokeminfo/vaje/poravnava2_nw_sw.html -> Možnosti za ujemanja/neujemanja

Screenshot: 
![image](https://user-images.githubusercontent.com/20877556/160234410-6a82e9b5-616f-4b00-85fe-5d4287e27659.png)

Firefox 98.0.1 in Chrome 99.0.4844.82 (kar je logično, saj je v datoteki .html tabela zapisana kot navadno besedilo namesto kot tabela)

**Comment by mpavsic** [comment]
Fixed! There was a problem with `:` specifying cell alignment.
